server:
  port: 8080

spring:
  application:
    name: ReadMyPDF

  docker:
    compose:
      enabled: false

#  datasource:
#    url: jdbc:postgresql://localhost:5432/readmypdf
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
#    hikari:
#      connection-timeout: 30000
#      maximum-pool-size: 10
#      minimum-idle: 5
#
#  jpa:
#    hibernate:
#      ddl-auto: create
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.PostgreSQLDialect
#        format_sql: true

telegram:
  bot:
    token: "7616022774:AAG-RFM_kLS_j7-D_QbpC_HGAgGcseXjGSk"
    username: "ReadMyPdfBot"

logging:
  level:
    com.PDFBot: INFO
    org.springframework: WARN
  pattern:
    console: "%d{HH:mm:ss} %-5level - %msg%n"

bot:
  start:
    message: "Привет, %s! Я ReadMyPDF бот!\n\nПросто отправь мне PDF файл, и я извлеку из него текст!"
  help:
    message: "Помощь по использованию:\n\n1. Отправь мне PDF файл (до 10MB)\n2. Я проверю файл\n3. Извлеку текст\n4. Верну результат"
  status:
    message: "Система работает нормально\nВерсия: 1.0.0"
  default:
    message: "Отправь мне PDF файл или используй /help"
  document:
    received: "Получил файл: %s\nОт: %s\nРазмер: %.2f MB\nОбрабатываю..."
    error: "Ошибка: %s"